name: do-prototype-app
region: sfo
services:
- name: api
  github:
    repo: YOUR_GITHUB_USERNAME/project-template
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
